language: cpp

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-4.9
            - cmake-data
            - cmake
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
  - sudo apt-get install libssl-dev libgmp-dev -y
  - eval "${MATRIX_EVAL}"
  - git clone https://github.com/emp-toolkit/emp-readme.git
  - bash ./emp-readme/scripts/install_relic.sh
  - bash ./emp-readme/scripts/install_emp-tool.sh
  - bash ./emp-readme/scripts/install_emp-ot.sh

addons:

script:
  - cmake -DCMAKE_BUILD_TYPE=Debug . && make 